### ISSUE TITLE
Safe-areas doesent work with Nuxt3

### ISSUE THREAD

**Issue by victorpahuus** [konstaui/konsta-nuxt3-starter#6]
I was working on my application when I realized that the iPhone's notch is eating the navbar. After reading your documentation on safe-areas, it still doesn't work. I tried using your Nuxt3 Starter project and only installed Capacitor, and the navbar is still behind the notch, and are not adjusting it to the screen.

I have not been able to find others who have had the same problem in the past, and hope you can clarify where it goes wrong, or if it just mysteriously does not work for me.
<img width="371" alt="Nuxt3 Konsta UI navbar notch" src="https://github.com/user-attachments/assets/4921a8dd-1304-43d4-a554-1e14eb55b8a4">

**Comment by rakuraev** [comment]
> I was working on my application when I realized that the iPhone's notch is eating the navbar. After reading your documentation on safe-areas, it still doesn't work. I tried using your Nuxt3 Starter project and only installed Capacitor, and the navbar is still behind the notch, and are not adjusting it to the screen.
> 
> I have not been able to find others who have had the same problem in the past, and hope you can clarify where it goes wrong, or if it just mysteriously does not work for me. <img alt="Nuxt3 Konsta UI navbar notch" width="371" src="https://private-user-images.githubusercontent.com/49293748/369858034-4921a8dd-1304-43d4-a554-1e14eb55b8a4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1MTI1NTksIm5iZiI6MTcyOTUxMjI1OSwicGF0aCI6Ii80OTI5Mzc0OC8zNjk4NTgwMzQtNDkyMWE4ZGQtMTMwNC00M2Q0LWE1NTQtMWUxNGViNTViOGE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIxVDEyMDQxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY5OGMzZjMyYjNmYWE1MDI0MGFlMWUwOWE1YTg0NWM2MmM3OGM5MDI5YWRiZGZlMjdjZThjOTFhODc0NDlhZTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.7YA0O97Crwu3dRv4xyF5Mud-TfiVqcXcF5b0ZL0JFcA">

Add this in nuxt.config.ts
```ts
export default defineNuxtConfig({
  app: {
    head: {
      meta: [
        {
          name: "viewport",
          content:
            "width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1, user-scalable=no, viewport-fit=cover",
        },
      ],
    },
  },
  ```
  
works for me 
  
![CleanShot 2024-10-21 at 15 06 27](https://github.com/user-attachments/assets/36456425-ef6f-40aa-ad97-aff6026d9a17)

**Comment by victorpahuus** [comment]
@rakuraev Awesome it seems to work! Thanks! :)
